# Generated by Django 2.2.7 on 2019-11-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20191116_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='holding_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='total_profit_loss',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='buy_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit_loss',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sell_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='volume',
            field=models.FloatField(),
        ),
    ]
