# Generated by Django 2.2.7 on 2019-11-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20191117_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buy_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='sell_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='volume',
            field=models.FloatField(null=True),
        ),
    ]
